### ISSUE TITLE
相关论文

### ISSUE THREAD

**Issue by jjjjstephen** [donkey3456/Digital-holography#4]
您好, 您的代码给我带来了很大的帮助。为了能够深入的了解代码中的原理，我想向你咨询一下是否有您发表的相关论文或者参看的论文。

**Comment by donkey3456** [comment]
好长时间不研究这个了，这是我最后一篇论文，https://opg.optica.org/ol/abstract.cfm?uri=ol-41-3-512
其他的论文都有被他引用
